services:
  # expo:
  #   build: ./app
  #   ports:
  #     - "19000:19000"  # Metro bundler (HTTP)
  #     - "19001:19001"  # Metro bundler (WebSocket)
  #     - "19002:19002"  # Expo DevTools
  #   volumes:
  #     - ./app:/app
  #   environment:
  #     - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: node testWeather.js  
    
    volumes:
    - ./backend:/app

  # nsql:
  #   build: ./nsql
  #   ports:
  #     - "3005:3005"
  #   env_file:
  #     - ./nsql/.env
  #   depends_on:
  #     - mongo

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: windly
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # mongo:
  #   image: mongo:7
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodata:/data/db

volumes:
  pgdata:
  mongodata: